apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: binding-selector
  description: The Binding Selector app allows multi-language stores, specifically
    those with a single-account, multiple-binding architecture, to switch
    between their configured bindings.
  tags:
    - typescript
  annotations:
    vtex.com/janus-acronym: ""
    vtex.com/o11y-os-index: ""
    grafana/dashboard-selector: ""
    github.com/project-slug: vtex-apps/binding-selector
    vtex.com/platform-flow-id: ""
    backstage.io/techdocs-ref: dir:../
    vtex.com/application-id: T8GDVMGA
spec:
  lifecycle: stable
  owner: te-0013
  type: frontend-ui
  dependsOn: []
