query bindingInfo {
  bindingInfo @context(provider: "vtex.binding-selector") {
    bindingId
    show
    translatedLocales {
      id
      label
      defaultLocale
      canonicalBaseAddress
      salesChannel
    }
    redirectUrlData {
      url
      redirectUrl
    }
  }
}
