mutation saveBindingInfo($data: [BindingsInput]) {
  saveBindingInfo(data: $data) {
    bindingId
    show
    translatedLocales {
      id
      label
      defaultLocale
      canonicalBaseAddress
      salesChannel
    }
    externalRedirectData {
      url
      redirectUrl
    }
  }
}
