mutation saveTranslatedInfo($bindingId: String, $translatedLocales: [TranslatedInfoArray]) {
  saveTranslatedInfo(bindingId: $bindingId, translatedLocales: $translatedLocales) {
      bindingId
      translatedLocales {
        id
        label
        defaultLocale
        canonicalBaseAddress
      }
  }
}