mutation saveTranslatedInfo($chosenId: String, $translatedLocales: [TranslatedInfoArray]) {
  saveTranslatedInfo(chosenId: $chosenId, translatedLocales: $translatedLocales) {
      chosenId
      translatedLocales {
        id
        label
        defaultLocale
        canonicalBaseAddress
      }
  }
}