mutation updateSalesChannel(
  $orderFormId: ID
  $salesChannel: String
  $locale: String
) {
  updateSalesChannel(
    orderFormId: $orderFormId
    salesChannel: $salesChannel
    locale: $locale
  ) @context(provider: "vtex.binding-selector") {
    orderFormId
    items {
      quantity
      uniqueId
    }
  }
}
